version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - BASE_URL=${BASE_URL}
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 